
/* (c) 2020 moltenform(Ben Fisher) */
/* Released under the MIT license */

/**
 * Feel free to change these as appropriate for your app name.
 */
export const msgScriptErr = 'Script Error: ';
export const msgInternalErr = 'Internal Error: ';
export const msgNotification = 'Simple Notification: ';
export const ui512InternalErr = 'ui512: ';
export const cProductName = 'ExampleProduct';
export const cAltProductName = 'ExampleProduct 1.0';

/* changes beyond this point are generated by set-tsconfig-flavor.js */

export const isProductionBuild = () => false;
